"""Add analysis column to incidents

Revision ID: 200f9ecf8a25
Revises: 88f8c9c586a6
Create Date: 2026-05-10 13:50:03.741222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200f9ecf8a25'
down_revision: Union[str, None] = '88f8c9c586a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'analysis')
    # ### end Alembic commands ###
