"""Add incidents table

Revision ID: 88f8c9c586a6
Revises: a3cc5c045e25
Create Date: 2026-05-10 09:24:52.142783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f8c9c586a6'
down_revision: Union[str, None] = 'a3cc5c045e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ANALYZING', 'ANALYZED', 'RESOLVED', 'IGNORED', name='incidentstatus'), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_service_id'), 'incidents', ['service_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_service_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
